version: "3"
services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - LOCAL_USER_ID=$LOCAL_USER_ID
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

  test-run:
    image: registry.gitlab.com/satoshilabs/trezor/trezor-suite/base:latest
    container_name: iframe-test-runner
    depends_on:
      - trezor-user-env-unix
    network_mode: service:trezor-user-env-unix
    environment:
      - LOCAL_USER_ID=$LOCAL_USER_ID
      - DISPLAY=$DISPLAY
      - HEADLESS=false
    working_dir: /trezor-suite
    command: bash -c "docker/wait-for-env.sh &&  yarn workspace @trezor/integration-tests test:connect-iframe"
    volumes:
      - ../:/trezor-suite
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
